version: "3.8"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - "7007:7007"

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    ports: 
      - '5432:5432'
    volumes:
      - app-db:/var/lib/postgresql/data
volumes:
  app-db: