version: "3.8"

services:
  app:
    build:
      context: .
    environment:
      APP_PORT: 7007
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: database
      DB_USER: postgres
      DB_PASS: password
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - "7007:7007"

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    ports: 
      - '5432:5432'
    volumes:
      - app-db:/var/lib/postgresql/data
volumes:
  app-db: